name: Mirror Repository

on:
  push:
    branches:
      - master

jobs:
  mirror-repository:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Mirror Bot'
        git config --global user.email 'mirror-bot@example.com'
    
    - name: Clone and Push to Mirror Repository
      env:
        SOURCE_REPO: ${{ github.repository }}
        MIRROR_REPO_URL: ${{ secrets.MIRROR_REPO_URL }}
        MIRROR_TOKEN: ${{ secrets.MIRROR_REPO_TOKEN }}
      run: |
        # Clone the source repository
        git clone --mirror https://github.com/$SOURCE_REPO.git source-repo
        
        # Change to the mirrored repository directory
        cd source-repo
        
        # Push to the mirror repository
        git push --mirror $MIRROR_REPO_URL