name: Mirror Repository

on:
  push:
    branches:
      - master

jobs:
  mirror-repository:
    runs-on: ubuntu-latest
    environment: mirror-repo
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Git
      env:
        GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}
        SOURCE_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"
    
    - name: Clone and Push to Mirror Repository
      env:
        SOURCE_REPO: ${{ github.repository }}
        MIRROR_REPO_URL: ${{ vars.MIRROR_REPO_URL }}
        SOURCE_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        MIRROR_TOKEN: ${{ secrets.MIRROR_REPO_TOKEN }}
      run: |
        # Clone the source repository using source repo token
        git clone --mirror https://${SOURCE_TOKEN}@github.com/$SOURCE_REPO.git source-repo
        
        # Change to the mirrored repository directory
        cd source-repo
        
        # Push all branches and tags, excluding pull request refs
        git push --mirror $MIRROR_REPO_URL \
          +refs/heads/*:refs/heads/* \
          +refs/tags/*:refs/tags/*
